const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE',
  UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE',
  CLEAR_CART_IN_FIREBASE: 'CLEAR_CART_IN_FIREBASE',
  CREATE_ORDER_IN_FIREBASE: 'CREATE_ORDER_IN_FIREBASE',
  NEW_ORDER: 'NEW_ORDER'
};

export default CartActionTypes;
