const WishActionTypes = {
  ADD_WISH_ITEM: 'ADD_WISH_ITEM',
  REMOVE_WISH_ITEM: 'REMOVE_WISH_ITEM',
  CLEAR_ITEM_FROM_WISH: 'CLEAR_ITEM_FROM_WISH',
  CLEAR_WISH: 'CLEAR_WISH',
  SET_WISH_FROM_FIREBASE: 'SET_WISH_FROM_FIREBASE',
  UPDATE_WISH_IN_FIREBASE: 'UPDATE_WISH_IN_FIREBASE'
};

export default WishActionTypes;
